# Generated by Django 4.1 on 2023-03-31 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sous_titre', models.TextField()),
                ('isprimary', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='firstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='Prions sans cesse', max_length=100, unique=True)),
                ('submain', models.TextField(default="Nous rependons la parole de Dieu qu'importe ou nous allons et nous agissons selon les prescriptions laisser par Jesus Christ")),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='fundRaiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('butArgent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('slug', models.CharField(max_length=60, null=True)),
                ('startupDate', models.DateField(auto_now=True)),
                ('show', models.BooleanField(default=True, null=True)),
                ('endlessFund', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='li_subtitle_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='secteur_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nos Secteurs', max_length=30, unique=True)),
                ('subtitle', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
                ('orator', models.CharField(max_length=20)),
                ('youtubeurl', models.TextField()),
                ('show', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Services', max_length=30, unique=True)),
                ('submenu', models.TextField(default='Nos horraires nous permettent de vous offrir une large evantaille de possibilitee pour vous de nous assister')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='statSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Notres statistique durants les deux dernier annees')),
                ('sat1Name', models.CharField(default='Membres', max_length=50)),
                ('sat2Name', models.CharField(default='Ministeres', max_length=50)),
                ('sat3Name', models.CharField(default='Missions', max_length=50)),
                ('sat4Name', models.CharField(default='Activites', max_length=50)),
                ('sat1', models.IntegerField()),
                ('sat2', models.IntegerField()),
                ('sat3', models.IntegerField()),
                ('sat4', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('anneCourante', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='verset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=15, unique=True)),
                ('verset', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wrapper_about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.TextField(null=True)),
                ('wrapper_about_page', models.ManyToManyField(blank=True, to='home.li_subtitle_about')),
            ],
        ),
        migrations.CreateModel(
            name='verset_main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, unique=True)),
                ('show', models.BooleanField(default=True)),
                ('v1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1', to='home.verset')),
                ('v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2', to='home.verset')),
                ('v3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3', to='home.verset')),
            ],
        ),
        migrations.CreateModel(
            name='serviceSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description_bref', models.TextField()),
                ('horraire', models.CharField(max_length=25)),
                ('show', models.BooleanField(default=True)),
                ('imageBackground', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
        ),
        migrations.CreateModel(
            name='Sermons_main_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nos Sermons', max_length=30, unique=True)),
                ('submenu', models.TextField(default='Profitez de nos Sermons')),
                ('show', models.BooleanField(default=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
                ('s1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s1', to='home.sermon')),
                ('s2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2', to='home.sermon')),
                ('s3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3', to='home.sermon')),
            ],
        ),
        migrations.AddField(
            model_name='sermon',
            name='tags',
            field=models.ManyToManyField(to='home.tag'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='tumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.CreateModel(
            name='secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='this is the default populated description', null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('titit', models.CharField(blank=True, max_length=50, null=True)),
                ('show', models.BooleanField(default=True, null=True)),
                ('quantity_of_members', models.IntegerField(default=0)),
                ('tumbail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
        ),
        migrations.CreateModel(
            name='participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField(auto_now=True)),
                ('isMember', models.BooleanField(null=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fundraiser')),
            ],
        ),
        migrations.CreateModel(
            name='paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(blank=True, null=True)),
                ('sous_titre', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('rang', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article')),
            ],
        ),
        migrations.CreateModel(
            name='heroSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39, unique=True)),
                ('heading', models.TextField()),
                ('submenu1', models.TextField()),
                ('submenu2', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='')),
                ('backgroud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
        ),
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('show', models.BooleanField(default=True)),
                ('vid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid1', to='home.herosingle')),
                ('vid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid2', to='home.herosingle')),
                ('vid3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid3', to='home.herosingle')),
            ],
        ),
        migrations.CreateModel(
            name='evenement_main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('subtitle', models.TextField()),
                ('show', models.BooleanField(default=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('startdate', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('isprimaray', models.BooleanField(default=False, null=True)),
                ('estimatedDuration', models.DurationField(null=True)),
                ('show', models.BooleanField(default=True)),
                ('fulldescription', models.TextField(null=True)),
                ('album', models.ManyToManyField(to='home.img')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Backgroud', to='home.img')),
                ('secteur', models.ManyToManyField(to='home.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='contact_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hero', models.CharField(default='Contactez Nous', max_length=30)),
                ('subtile_hero', models.TextField(default='Laissez nous un message, vos demande de prieres.')),
                ('title', models.CharField(default='Contactez Nous', max_length=30)),
                ('subtile', models.TextField(default="Qu'importe ou vous est dans le monde, la puissance du Seigneur reste et demeur le meme")),
                ('title2', models.CharField(default='Address', max_length=10)),
                ('address', models.CharField(default='Rue Louverture Rebecca prolongee #32', max_length=50)),
                ('telphone', models.CharField(default='+509 43 89 0007', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('isai_url', models.URLField(default='https://isai.up.railway.app')),
                ('siteweb', models.URLField()),
                ('youtube', models.URLField()),
                ('facebook', models.URLField()),
                ('horraire_dimanche_Matin', models.CharField(default='7h:00am - 10h:00am', max_length=25)),
                ('horraire_dimanche_apres_midi', models.CharField(default='5h:00m - 8h:00pm', max_length=25)),
                ('google_map', models.URLField()),
                ('show', models.BooleanField(default=True)),
                ('hero_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
        ),
        migrations.CreateModel(
            name='bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard1', max_length=50)),
                ('title_hero', models.CharField(default='Bay Bondye', max_length=50)),
                ('subtitle_hero', models.TextField(null=True)),
                ('show', models.BooleanField(default=True)),
                ('intro_title', models.CharField(max_length=50, null=True)),
                ('intro_subtitle', models.TextField(null=True)),
                ('verse_title', models.TextField(null=True)),
                ('verse_text', models.TextField(null=True)),
                ('fundraiser_title', models.TextField(null=True)),
                ('fundRaiser_subtitle', models.TextField(null=True)),
                ('fundraiser_button', models.CharField(max_length=50, null=True)),
                ('give_title', models.TextField(null=True)),
                ('give_subtitle', models.CharField(max_length=50, null=True)),
                ('give_text', models.TextField(null=True)),
                ('give_button', models.CharField(max_length=50, null=True)),
                ('hero_background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero', to='home.img')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.img'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='home.tag'),
        ),
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='standard', max_length=30)),
                ('title_hero', models.CharField(default='A propos de nous', max_length=30)),
                ('subtile_hero', models.TextField(default='Nous somme une eglise protestante situe en Haiti')),
                ('show', models.BooleanField(default=True)),
                ('hero_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
        ),
        migrations.CreateModel(
            name='live',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.evenement')),
                ('link', models.URLField()),
                ('autoclosed', models.BooleanField(default=False, null=True)),
                ('backgroud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img')),
            ],
            bases=('home.evenement',),
        ),
    ]
