# Generated by Django 4.1 on 2022-08-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heroSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39)),
                ('heading', models.TextField()),
                ('submenu1', models.TextField()),
                ('submenu2', models.CharField(max_length=50)),
                ('backgroud', models.ImageField(null=True, upload_to='images/%y')),
                ('video', models.FileField(null=True, upload_to='videos/%y')),
            ],
        ),
        migrations.CreateModel(
            name='secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('show', models.BooleanField(unique=True)),
                ('vid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid1', to='home.herosingle')),
                ('vid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid2', to='home.herosingle')),
                ('vid3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid3', to='home.herosingle')),
            ],
        ),
    ]
