# Generated by Django 4.1 on 2022-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hero_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosingle',
            name='backgroud',
            field=models.ImageField(null=True, upload_to='media/images/%y'),
        ),
        migrations.AlterField(
            model_name='herosingle',
            name='video',
            field=models.FileField(null=True, upload_to='media/videos/%y'),
        ),
    ]
