# Generated by Django 4.1 on 2022-09-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_firstsection_fundraiser_horaires_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='butArgent',
        ),
    ]
