# Generated by Django 4.1 on 2023-09-17 18:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='article',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AddField(
            model_name='article',
            name='paragraphs',
            field=ckeditor.fields.RichTextField(default='hi'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='paragraph',
        ),
    ]
