# Generated by Django 4.1 on 2022-08-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_herosingle_backgroud_alter_herosingle_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('startdate', models.DurationField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='firstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='Prions sans cesse', max_length=100, unique=True)),
                ('submain', models.TextField(default="Nous rependons la parole de Dieu qu'importe ou nous allons et nous agissons selon les prescriptions laisser par Jesus Christ")),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='secteur_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nos Secteurs', max_length=30)),
                ('subtitle', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('orator', models.CharField(max_length=20)),
                ('tumbnail', models.FileField(upload_to='media/images/%y')),
                ('youtubeurl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Services', max_length=30)),
                ('submenu', models.TextField(default='Nos horraires nous permettent de vous offrir une large evantaille de possibilitee pour vous de nous assister')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('imageBackground', models.FileField(null=True, upload_to='media/images/%y')),
                ('description_bref', models.TextField()),
                ('description', models.TextField()),
                ('horraire', models.CharField(max_length=15)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='statSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Notres statistique durants les deux dernier annees')),
                ('sat1Name', models.CharField(default='Membres', max_length=50)),
                ('sat2Name', models.CharField(default='Ministeres', max_length=50)),
                ('sat3Name', models.CharField(default='Missions', max_length=50)),
                ('sat4Name', models.CharField(default='Activites', max_length=50)),
                ('sat1', models.IntegerField()),
                ('sat2', models.IntegerField()),
                ('sat3', models.IntegerField()),
                ('sat4', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='verset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=15)),
                ('verset', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='secteur',
            name='name',
        ),
        migrations.RemoveField(
            model_name='secteur',
            name='show',
        ),
        migrations.AddField(
            model_name='secteur',
            name='description',
            field=models.TextField(blank=True, default='this is the default populated description', null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='slug',
            field=models.SlugField(blank=True, default='this is the default populated slug', null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='titit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='tumbail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='herosingle',
            name='name',
            field=models.CharField(max_length=39, unique=True),
        ),
        migrations.CreateModel(
            name='verset_main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True)),
                ('v1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v1', to='home.verset')),
                ('v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2', to='home.verset')),
                ('v3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3', to='home.verset')),
            ],
        ),
        migrations.CreateModel(
            name='Sermons_main_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nos Sermons', max_length=30)),
                ('submenu', models.TextField(default='Profitez de nos Sermons')),
                ('show', models.BooleanField(default=True)),
                ('s1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s1', to='home.sermon')),
                ('s2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2', to='home.sermon')),
                ('s3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3', to='home.sermon')),
            ],
        ),
        migrations.CreateModel(
            name='evenement_main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.TextField()),
                ('show', models.BooleanField(default=True)),
                ('e1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e1', to='home.evenement')),
                ('e2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e2', to='home.evenement')),
                ('e3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e3', to='home.evenement')),
            ],
        ),
    ]
