# Generated by Django 4.1 on 2022-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_fundraiser_butargent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infogeneral',
            name='name',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='butArgent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
