# Generated by Django 4.1 on 2022-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_evenement_firstsection_secteur_main_sermon_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsection',
            name='anneCourante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
