# Generated by Django 4.1 on 2022-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_infogeneral_name_fundraiser_butargent'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogeneral',
            name='name',
            field=models.CharField(default='Stantard', max_length=30),
        ),
    ]
