# Generated by Django 4.1 on 2022-08-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_statsection_annecourante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesingle',
            old_name='name',
            new_name='title',
        ),
    ]
