# Generated by Django 4.1 on 2022-08-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_name_servicesingle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evenement_main_page',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='description',
            field=models.TextField(blank=True, default='this is the default populated description', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='secteur_main',
            name='title',
            field=models.CharField(default='Nos Secteurs', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sermons_main_section',
            name='title',
            field=models.CharField(default='Nos Sermons', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Services', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='verset',
            name='ref',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='verset_main_page',
            name='theme',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
