# Generated by Django 4.1 on 2022-09-16 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article_story_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeparagraph'),
        ),
    ]
