# Generated by Django 4.1 on 2022-08-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_evenement_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.FileField(upload_to='media/images/%y')),
                ('title_hero', models.CharField(default='Contactez Nous', max_length=30)),
                ('subtile_hero', models.TextField(default='Laissez nous un message, vos demande de prieres.')),
                ('title', models.CharField(default='Contactez Nous', max_length=30)),
                ('subtile', models.TextField(default="Qu'importe ou vous est dans le monde, la puissance du Seigneur reste et demeur le meme")),
                ('title2', models.CharField(default='Address', max_length=10)),
                ('subtitle', models.CharField(default='Rue Louverture Rebecca prolongee #32', max_length=30)),
                ('telphone', models.CharField(default='+509 43 89 0007', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('siteweb', models.CharField(max_length=20)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='secteur',
            name='tumbail',
            field=models.FileField(null=True, upload_to='media/images/%y'),
        ),
    ]
