# Generated by Django 4.1 on 2022-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_typeparagraph_alter_paragraph_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='apercu',
            field=models.BooleanField(default=False),
        ),
    ]
