# Generated by Django 4.1 on 2022-08-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_page_alter_secteur_tumbail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_page',
            name='subtitle',
            field=models.CharField(default='Rue Louverture Rebecca prolongee #32', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='telphone',
            field=models.CharField(default='+509 43 89 0007', max_length=30),
        ),
    ]
