# Generated by Django 4.1 on 2022-08-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_subtitle_contact_page_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='standard', max_length=30)),
                ('hero_img', models.FileField(upload_to='media/images/%y')),
                ('title_hero', models.CharField(default='A propos de nous', max_length=30)),
                ('subtile_hero', models.TextField(default='Nous somme une eglise protestante situe en Haiti')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='wrapper_about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='li_subtitle_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('wrapper_about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wrapper_about_page')),
            ],
        ),
    ]
