# Generated by Django 4.1 on 2022-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_about_page_wrapper_about_page_li_subtitle_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='li_subtitle_about',
            name='wrapper_about_page',
        ),
        migrations.AddField(
            model_name='li_subtitle_about',
            name='wrapper_about_page',
            field=models.ManyToManyField(to='home.wrapper_about_page'),
        ),
    ]
