# Generated by Django 4.1 on 2022-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_li_subtitle_about_wrapper_about_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrapper_about_page',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='li_subtitle_about',
            name='paragraph',
            field=models.TextField(null=True),
        ),
    ]
