# Generated by Django 4.1 on 2022-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_wrapper_about_page_paragraph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='li_subtitle_about',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='li_subtitle_about',
            name='wrapper_about_page',
        ),
        migrations.AddField(
            model_name='wrapper_about_page',
            name='paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wrapper_about_page',
            name='wrapper_about_page',
            field=models.ManyToManyField(to='home.li_subtitle_about'),
        ),
        migrations.AlterField(
            model_name='li_subtitle_about',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wrapper_about_page',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
