# Generated by Django 4.1 on 2022-08-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_li_subtitle_about_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement_main_page',
            name='background',
            field=models.FileField(null=True, upload_to='media/images/%y'),
        ),
        migrations.AlterField(
            model_name='wrapper_about_page',
            name='wrapper_about_page',
            field=models.ManyToManyField(blank=True, to='home.li_subtitle_about'),
        ),
    ]
