# Generated by Django 4.1 on 2022-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_evenement_main_page_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='startdate',
            field=models.DateField(),
        ),
    ]
