# Generated by Django 4.1 on 2022-08-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_evenement_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons_main_section',
            name='background',
            field=models.FileField(null=True, upload_to='media/images/%y'),
        ),
    ]
