# Generated by Django 4.1 on 2022-08-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sermons_main_section_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='live',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.evenement')),
                ('link', models.URLField()),
            ],
            bases=('home.evenement',),
        ),
        migrations.AddField(
            model_name='evenement',
            name='isprimaray',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
