# Generated by Django 4.1 on 2022-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_live_evenement_isprimaray_alter_evenement_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
