# Generated by Django 4.1 on 2022-08-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_evenement_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='tumnail',
            field=models.ImageField(null=True, upload_to='media/images/%y'),
        ),
    ]
