# Generated by Django 4.1 on 2022-08-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_bay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/images/%y')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='estimatedDuration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='li_subtitle_about',
            name='show',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='autoclosed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='show',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='show',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='album',
            field=models.ManyToManyField(null=True, to='home.img'),
        ),
    ]
