# Generated by Django 4.1 on 2022-08-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_evenement_cover_img_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Backgroud', to='home.img'),
        ),
    ]
