# Generated by Django 4.1 on 2022-08-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_evenement_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='fulldescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
