# Generated by Django 4.1 on 2022-08-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_evenement_fulldescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='hero_background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero', to='home.img'),
        ),
    ]
