# Generated by Django 4.1 on 2022-08-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_bay_hero_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='fundRaiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('But', models.CharField(max_length=50)),
                ('butArgent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('participants', models.ManyToManyField(to='home.participant')),
            ],
        ),
    ]
