# Generated by Django 4.1 on 2022-08-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_participant_fundraiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='participants',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='startupDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='participant',
        ),
        migrations.AddField(
            model_name='participation',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fundraiser'),
        ),
    ]
