# Generated by Django 4.1 on 2022-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_participation_remove_fundraiser_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='show',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
