# Generated by Django 4.1 on 2022-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_fundraiser_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='isMember',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='But',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
