# Generated by Django 4.1 on 2022-08-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_participation_ismember_alter_fundraiser_but'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='endlessFund',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
