# Generated by Django 4.1 on 2022-08-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_but_fundraiser_title_fundraiser_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='title',
            new_name='But',
        ),
    ]
