# Generated by Django 4.1 on 2022-08-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_title_fundraiser_but'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='But',
            new_name='title',
        ),
    ]
