# Generated by Django 4.1 on 2022-08-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_but_fundraiser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
