# Generated by Django 4.1 on 2022-08-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_fundraiser_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='startdate',
        ),
    ]
