# Generated by Django 4.1 on 2022-08-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_fundraiser_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='fundRaiser_subtitle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='fundraiser_button',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='fundraiser_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='give_button',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='give_subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='give_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='give_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='intro_subtitle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='intro_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='verse_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bay',
            name='verse_title',
            field=models.TextField(null=True),
        ),
    ]
