# Generated by Django 4.1 on 2022-08-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_bay_fundraiser_subtitle_bay_fundraiser_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement_main_page',
            name='e1',
        ),
        migrations.RemoveField(
            model_name='evenement_main_page',
            name='e2',
        ),
        migrations.RemoveField(
            model_name='evenement_main_page',
            name='e3',
        ),
    ]
