# Generated by Django 4.1 on 2022-08-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_evenement_main_page_e1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='slug',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
