# Generated by Django 4.1 on 2022-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_sermon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
