# Generated by Django 4.1 on 2022-08-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_tag_sermon_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
