# Generated by Django 4.1 on 2022-08-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_tag_slug_alter_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='tumnail',
        ),
        migrations.AddField(
            model_name='live',
            name='backgroud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='hero_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='hero_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='evenement_main_page',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='herosingle',
            name='backgroud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='herosingle',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='tumbail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='tumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='sermons_main_section',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
        migrations.AlterField(
            model_name='servicesingle',
            name='imageBackground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.img'),
        ),
    ]
