# Generated by Django 4.1 on 2022-08-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_live_tumnail_live_backgroud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesingle',
            name='description_bref',
        ),
        migrations.RemoveField(
            model_name='servicesingle',
            name='horraire',
        ),
        migrations.AddField(
            model_name='secteur',
            name='events',
            field=models.ManyToManyField(to='home.evenement'),
        ),
    ]
