# Generated by Django 4.1 on 2023-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_live_tumnail_live_backgroud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='secteur',
            field=models.ManyToManyField(to='home.secteur'),
        ),
        migrations.AddField(
            model_name='secteur',
            name='quantity_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
