# Generated by Django 4.1 on 2022-08-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_servicesingle_description_bref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='siteweb',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, to='home.img2'),
        ),
    ]
