# Generated by Django 4.1 on 2023-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_article_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='album',
            field=models.ManyToManyField(to='home.img'),
        ),
    ]
