# Generated by Django 4.1 on 2022-08-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_img2_alter_contact_page_siteweb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosingle',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
