# Generated by Django 4.1 on 2023-03-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_evenement_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.img'),
        ),
    ]
