# Generated by Django 4.1 on 2023-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_article_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='sous_titre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesingle',
            name='horraire',
            field=models.CharField(max_length=25),
        ),
    ]
