# Generated by Django 4.1 on 2023-03-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_paragraph_sous_titre_alter_paragraph_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesingle',
            name='description',
        ),
    ]
