# Generated by Django 4.1 on 2023-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_remove_servicesingle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_page',
            name='google_map',
            field=models.URLField(default='http://127.0.0.1:8000/home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_page',
            name='horraire_dimanche_Matin',
            field=models.CharField(default='7h:00am - 10h:00am', max_length=25),
        ),
        migrations.AddField(
            model_name='contact_page',
            name='horraire_dimanche_apres_midi',
            field=models.CharField(default='5h:00m - 8h:00pm', max_length=25),
        ),
        migrations.AlterField(
            model_name='contact_page',
            name='siteweb',
            field=models.URLField(),
        ),
    ]
