# Generated by Django 4.1 on 2023-03-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_contact_page_google_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_page',
            name='isai_url',
            field=models.URLField(default='https://isai.up.railway.app'),
        ),
    ]
