# Generated by Django 4.1 on 2023-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_contact_page_isai_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_page',
            name='facebook',
            field=models.URLField(default='https://isai.up.railway.app'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_page',
            name='youtube',
            field=models.URLField(default='https://isai.up.railway.app'),
            preserve_default=False,
        ),
    ]
